# Generated by Django 6.1 on 2026-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='service',
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес / район'),
        ),
        migrations.AddField(
            model_name='lead',
            name='device_model',
            field=models.CharField(blank=True, max_length=150, verbose_name='Марка и модель'),
        ),
        migrations.AddField(
            model_name='lead',
            name='device_type',
            field=models.CharField(blank=True, choices=[('printer', 'Принтер'), ('mfp', 'МФУ'), ('scanner', 'Сканер'), ('plotter', 'Плоттер'), ('other', 'Другое')], max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='lead',
            name='issue',
            field=models.TextField(blank=True, verbose_name='Неисправность'),
        ),
    ]
