# Generated by Django 6.1 on 2026-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_lead_comment_remove_lead_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.AddField(
            model_name='lead',
            name='consent',
            field=models.BooleanField(default=1, verbose_name='Согласие на обработку данных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='issue',
            field=models.TextField(blank=True, verbose_name='Что с принтером'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Как к вам обращаться'),
        ),
    ]
